export type SassVariableCategory = 'core' | 'form' | 'actions' | 'feedback' | 'data' | 'navigation' | 'layout'

export interface SassVariableDefinition {
  name: string
  category: SassVariableCategory
}

export const SASS_VARIABLE_CATEGORY_LABELS: Record<SassVariableCategory, string> = {
  core: 'Core',
  form: 'Form',
  actions: 'Actions',
  feedback: 'Feedback',
  data: 'Data',
  navigation: 'Navigation',
  layout: 'Layout',
}

export const SASS_VARIABLES = [
  { name: 'colors', category: 'core' },
  { name: 'color-white', category: 'core' },
  { name: 'color-black', category: 'core' },
  { name: 'color-primary', category: 'core' },
  { name: 'color-success', category: 'core' },
  { name: 'color-warning', category: 'core' },
  { name: 'color-danger', category: 'core' },
  { name: 'color-error', category: 'core' },
  { name: 'color-info', category: 'core' },
  { name: 'text-color', category: 'core' },
  { name: 'border-color', category: 'core' },
  { name: 'fill-color', category: 'core' },
  { name: 'bg-color', category: 'core' },
  { name: 'border-width', category: 'core' },
  { name: 'border-style', category: 'core' },
  { name: 'border-color-hover', category: 'core' },
  { name: 'border-radius', category: 'core' },
  { name: 'box-shadow', category: 'core' },
  { name: 'font-family', category: 'core' },
  { name: 'font-size', category: 'core' },
  { name: 'z-index', category: 'core' },
  { name: 'disabled', category: 'core' },
  { name: 'common-component-size', category: 'core' },
  { name: 'overlay-color', category: 'core' },
  { name: 'mask-color', category: 'core' },
  { name: 'checkbox', category: 'form' },
  { name: 'checkbox-button', category: 'form' },
  { name: 'checkbox-bordered-padding-left', category: 'form' },
  { name: 'checkbox-bordered-padding-right', category: 'form' },
  { name: 'radio', category: 'form' },
  { name: 'radio-height', category: 'form' },
  { name: 'radio-button', category: 'form' },
  { name: 'radio-disabled', category: 'form' },
  { name: 'radio-checked', category: 'form' },
  { name: 'radio-bordered-input-height', category: 'form' },
  { name: 'radio-bordered-input-width', category: 'form' },
  { name: 'select', category: 'form' },
  { name: 'select-option', category: 'form' },
  { name: 'select-group', category: 'form' },
  { name: 'select-dropdown', category: 'form' },
  { name: 'select-wrapper-padding', category: 'form' },
  { name: 'select-near-margin-left', category: 'form' },
  { name: 'select-item-gap', category: 'form' },
  { name: 'select-item-height', category: 'form' },
  { name: 'alert', category: 'feedback' },
  { name: 'messagebox', category: 'feedback' },
  { name: 'message', category: 'feedback' },
  { name: 'notification', category: 'feedback' },
  { name: 'input', category: 'form' },
  { name: 'input-disabled', category: 'form' },
  { name: 'input-font-size', category: 'form' },
  { name: 'input-height', category: 'form' },
  { name: 'input-line-height', category: 'form' },
  { name: 'input-number-width', category: 'form' },
  { name: 'input-otp-gap', category: 'form' },
  { name: 'input-otp', category: 'form' },
  { name: 'input-padding-horizontal', category: 'form' },
  { name: 'cascader', category: 'form' },
  { name: 'cascader-item-gap', category: 'form' },
  { name: 'cascader-wrapper-padding', category: 'form' },
  { name: 'cascader-item-height', category: 'form' },
  { name: 'cascader-search-input-margin-left', category: 'form' },
  { name: 'cascader-dropdown', category: 'form' },
  { name: 'statistic', category: 'data' },
  { name: 'button', category: 'actions' },
  { name: 'button-border-width', category: 'actions' },
  { name: 'button-border-color', category: 'actions' },
  { name: 'button-bg-color', category: 'actions' },
  { name: 'button-text-color', category: 'actions' },
  { name: 'button-font-size', category: 'actions' },
  { name: 'button-border-radius', category: 'actions' },
  { name: 'button-padding-vertical', category: 'actions' },
  { name: 'button-padding-horizontal', category: 'actions' },
  { name: 'switch', category: 'form' },
  { name: 'dialog', category: 'feedback' },
  { name: 'tour', category: 'feedback' },
  { name: 'anchor', category: 'navigation' },
  { name: 'segmented', category: 'form' },
  { name: 'mention', category: 'form' },
  { name: 'input-tag', category: 'form' },
  { name: 'input-tag-padding', category: 'form' },
  { name: 'input-tag-inner-padding', category: 'form' },
  { name: 'input-tag-gap', category: 'form' },
  { name: 'table', category: 'data' },
  { name: 'table-font-size', category: 'data' },
  { name: 'table-padding', category: 'data' },
  { name: 'table-cell-padding', category: 'data' },
  { name: 'pagination', category: 'data' },
  { name: 'popup', category: 'feedback' },
  { name: 'popover', category: 'feedback' },
  { name: 'popper', category: 'feedback' },
  { name: 'skeleton', category: 'data' },
  { name: 'tag', category: 'data' },
  { name: 'tag-height', category: 'data' },
  { name: 'tag-padding', category: 'data' },
  { name: 'tag-icon-size', category: 'data' },
  { name: 'text', category: 'data' },
  { name: 'text-font-size', category: 'data' },
  { name: 'tree', category: 'data' },
  { name: 'dropdown', category: 'navigation' },
  { name: 'drawer', category: 'feedback' },
  { name: 'badge', category: 'data' },
  { name: 'card', category: 'data' },
  { name: 'slider', category: 'layout' },
  { name: 'menu', category: 'navigation' },
  { name: 'rate', category: 'data' },
  { name: 'colorpicker', category: 'data' },
  { name: 'datepicker', category: 'layout' },
  { name: 'date-editor', category: 'layout' },
  { name: 'loading', category: 'feedback' },
  { name: 'scrollbar', category: 'layout' },
  { name: 'carousel', category: 'data' },
  { name: 'collapse', category: 'data' },
  { name: 'transfer', category: 'data' },
  { name: 'timeline', category: 'data' },
  { name: 'tabs', category: 'navigation' },
  { name: 'backtop', category: 'feedback' },
  { name: 'link', category: 'navigation' },
  { name: 'link-text-color', category: 'navigation' },
  { name: 'calendar', category: 'data' },
  { name: 'form', category: 'form' },
  { name: 'avatar', category: 'data' },
  { name: 'avatar-size', category: 'data' },
  { name: 'avatar-group', category: 'data' },
  { name: 'empty', category: 'data' },
  { name: 'descriptions', category: 'data' },
  { name: 'result', category: 'feedback' },
  { name: 'upload', category: 'data' },
  { name: 'transition', category: 'layout' },
  { name: 'transition-duration', category: 'layout' },
  { name: 'transition-function', category: 'layout' },
  { name: 'header', category: 'layout' },
  { name: 'main', category: 'layout' },
  { name: 'footer', category: 'layout' },
  { name: 'sm', category: 'core' },
  { name: 'md', category: 'core' },
  { name: 'lg', category: 'core' },
  { name: 'xl', category: 'core' },
  { name: 'breakpoints', category: 'core' },
  { name: 'breakpoints-spec', category: 'core' },
] as const satisfies readonly SassVariableDefinition[]

export const SASS_VARIABLE_NAMES = SASS_VARIABLES.map((variable) => variable.name)

export const SASS_VARIABLE_NAME_SET = new Set<string>(SASS_VARIABLE_NAMES)

export function createEmptyScssOverrides(): Record<string, string> {
  return Object.fromEntries(SASS_VARIABLE_NAMES.map((name) => [name, '']))
}
